# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui0_ver1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1379, 881)
        Form.setMinimumSize(QtCore.QSize(1379, 0))
        Form.setAccessibleDescription("")
        self.graphicsView = PlotWidget(Form)
        self.graphicsView.setGeometry(QtCore.QRect(26, 24, 1321, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = PlotWidget(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(475, 420, 431, 411))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = PlotWidget(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(915, 420, 431, 411))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = PlotWidget(Form)
        self.graphicsView_4.setGeometry(QtCore.QRect(30, 420, 441, 201))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = PlotWidget(Form)
        self.graphicsView_5.setGeometry(QtCore.QRect(30, 620, 441, 171))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 839, 810, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_read_file = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_read_file.setObjectName("pB_read_file")
        self.horizontalLayout.addWidget(self.pB_read_file)
        self.comboBox_port_com = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_port_com.setObjectName("comboBox_port_com")
        self.horizontalLayout.addWidget(self.comboBox_port_com)
        self.pB_read = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_read.setObjectName("pB_read")
        self.horizontalLayout.addWidget(self.pB_read)
        self.pB_close = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_close.setObjectName("pB_close")
        self.horizontalLayout.addWidget(self.pB_close)
        self.pB_pwm = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_pwm.setEnabled(True)
        self.pB_pwm.setObjectName("pB_pwm")
        self.horizontalLayout.addWidget(self.pB_pwm)
        self.pB_U = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_U.setEnabled(True)
        self.pB_U.setStyleSheet("")
        self.pB_U.setObjectName("pB_U")
        self.horizontalLayout.addWidget(self.pB_U)
        self.pB_release = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_release.setStyleSheet("")
        self.pB_release.setObjectName("pB_release")
        self.horizontalLayout.addWidget(self.pB_release)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 800, 431, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)

        self.retranslateUi(Form)
        self.pB_read.pressed.connect(self.pB_read.show) # type: ignore
        self.pB_read.pressed.connect(self.pB_pwm.show) # type: ignore
        self.pushButton.pressed.connect(Form.close) # type: ignore
        self.pB_read.pressed.connect(self.pB_U.show) # type: ignore
        self.pB_close.pressed.connect(self.pB_pwm.hide) # type: ignore
        self.pB_release.pressed.connect(self.pB_U.show) # type: ignore
        self.pB_close.pressed.connect(self.pB_read.show) # type: ignore
        self.pB_close.pressed.connect(self.pB_U.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PEM Stack"))
        self.pB_read_file.setText(_translate("Form", "Plot file"))
        self.pB_read.setText(_translate("Form", "Start read sensors"))
        self.pB_close.setText(_translate("Form", "Close read sensors"))
        self.pB_pwm.setText(_translate("Form", "PWM input"))
        self.pB_U.setText(_translate("Form", "Step input"))
        self.pB_release.setText(_translate("Form", "Release Step"))
        self.pushButton.setText(_translate("Form", "Exit"))
        self.label.setText(_translate("Form", "Experiment: "))
        self.lineEdit.setText(_translate("Form", "experiment_1"))
from pyqtgraph import PlotWidget
